export const users = [
  {
    id: 1,
    username: "Jean",
    email: "jean@email.com",
    age: 30,
    imgPath: "/img/user1.jpg",
    cars: [
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
    ],
  },
  {
    id: 2,
    username: "Pascal",
    email: "pascal@email.com",
    age: 25,
    imgPath: "/img/user2.jpg",
    cars: [
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
    ],
  },
  {
    id: 3,
    username: "Nacim",
    email: "nacim@email.com",
    age: 38,
    imgPath: "/img/user3.jpg",
    cars: [
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
    ],
  },
  {
    id: 4,
    username: "Riles",
    email: "riles@email.com",
    age: 3,
    imgPath: "/img/user4.jpg",
    cars: [
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
    ],
  },
  {
    id: 5,
    username: "Lyna",
    email: "lyna@email.com",
    age: 5,
    imgPath: "/img/user5.jpg",
    cars: [
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
    ],
  },
  {
    id: 6,
    username: "Said",
    email: "said@email.com",
    age: 36,
    imgPath: "/img/user6.jpg",
    cars: [
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
      {
        id: 2,
        model: "Corrola",
        constructor: "Toyota",
        year: 2020,
        color: "Blue",
        imgPath: "/img/car2.jpg",
      },
    ],
  },
];

const getAllUsers = () => {};
