export const cars = [
  {
    id: 1,
    model: "B-Max",
    constructor: "Ford",
    year: 2014,
    color: "White",
    imgPath: "./assets/img/car1.jpg",
  },
  {
    id: 2,
    model: "Corrola",
    constructor: "Toyota",
    year: 2020,
    color: "Blue",
    imgPath: "./assets/img/car2.jpg",
  },
  {
    id: 3,
    model: "Ibiza",
    constructor: "Seat",
    year: 2005,
    color: "Black",
    imgPath: "./assets/img/car3.jpg",
  },
  {
    id: 4,
    model: "406",
    constructor: "Peugeot",
    year: 2008,
    color: "Green",
    imgPath: "./assets/img/car4.jpg",
  },
  {
    id: 5,
    model: "Megane",
    constructor: "Reneault",
    year: 2018,
    color: "Red",
    imgPath: "./assets/img/car5.jpg",
  },
];
